name: Continuous testing and publication to NPM from 'main'

on: 
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  publish-js-package:
    runs-on: ubuntu-latest
    if: (github.ref_name == 'main')

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish JS release
        uses: ./actions/js/publish
        with:
          node-version: 14.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}

